In [53]:
!pip install finvader

Requirement already satisfied: finvader in /opt/anaconda3/envs/Erdos-DS-2024-newsworthy/lib/python3.11/site-packages (1.0.4)
Requirement already satisfied: nltk==3.6.2 in /opt/anaconda3/envs/Erdos-DS-2024-newsworthy/lib/python3.11/site-packages (from finvader) (3.6.2)
Requirement already satisfied: click in /opt/anaconda3/envs/Erdos-DS-2024-newsworthy/lib/python3.11/site-packages (from nltk==3.6.2->finvader) (8.1.7)
Requirement already satisfied: joblib in /opt/anaconda3/envs/Erdos-DS-2024-newsworthy/lib/python3.11/site-packages (from nltk==3.6.2->finvader) (1.4.2)
Requirement already satisfied: regex in /opt/anaconda3/envs/Erdos-DS-2024-newsworthy/lib/python3.11/site-packages (from nltk==3.6.2->finvader) (2024.5.15)
Requirement already satisfied: tqdm in /opt/anaconda3/envs/Erdos-DS-2024-newsworthy/lib/python3.11/site-packages (from nltk==3.6.2->finvader) (4.66.4)

In [54]:
import pandas as pd
import os
from datetime import datetime, timedelta
import datetime as dt
import numpy as np
from finvader import finvader as fv

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /Users/sultanitw/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [2]:
df_articles = pd.read_csv('data/outdated/data_finvader.csv')
df_articles.drop(columns = ['Unnamed: 0.1','Unnamed: 0'], inplace = True)
df_articles['Date & Time'] = pd.to_datetime(df_articles['Date & Time'], utc = True)
df_articles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63704 entries, 0 to 63703
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date & Time    63704 non-null  datetime64[ns, UTC]
 1   Date           63704 non-null  object
 2   Time           63704 non-null  object
 3   Ticker         63704 non-null  object
 4   Sector         63704 non-null  object
 5   Source         63704 non-null  object
 6   sentiment_neg  63704 non-null  float64
 7   sentiment_neu  63704 non-null  float64
 8   sentiment_pos  63704 non-null  float64
 9   sentiment_tot  63704 non-null  float64
 10  Headline       63704 non-null  object
 11  Text           63704 non-null  object
 12  URL            63704 non-null  object
 13  finvader       63704 non-null  float64
dtypes: datetime64[ns, UTC](1), float64(5), object(8)
memory usage: 6.8+ MB

In [47]:
#article dataset had a duplicate 
check = df_articles.duplicated(keep = False)
check[check == True]
df_articles.iloc[23124], df_articles.iloc[23123]
df_articles = df_articles.drop_duplicates()
df_articles.info()

<class 'pandas.core.frame.DataFrame'>
Index: 63703 entries, 0 to 63703
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date & Time    63703 non-null  datetime64[ns, UTC]
 1   Date           63703 non-null  object
 2   Time           63703 non-null  object
 3   Ticker         63703 non-null  object
 4   Sector         63703 non-null  object
 5   Source         63703 non-null  object
 6   sentiment_neg  63703 non-null  float64
 7   sentiment_neu  63703 non-null  float64
 8   sentiment_pos  63703 non-null  float64
 9   sentiment_tot  63703 non-null  float64
 10  Headline       63703 non-null  object
 11  Text           63703 non-null  object
 12  URL            63703 non-null  object
 13  finvader       63703 non-null  float64
dtypes: datetime64[ns, UTC](1), float64(5), object(8)
memory usage: 7.3+ MB

In [55]:
def fin_sentiment_score(headline:str, abstract:str, version:str):
    txt = headline + ' ' + abstract
    return fv(text = txt, use_henry= True, use_sentibignomics=True, indicator= version)

In [64]:
df_articles['finvader_neg'] = df_articles.apply(lambda x: fin_sentiment_score(x['Headline'], x['Text'], 'neg'), axis = 1)
df_articles['finvader_neu'] = df_articles.apply(lambda x: fin_sentiment_score(x['Headline'], x['Text'], 'neu'), axis = 1)
df_articles['finvader_pos'] = df_articles.apply(lambda x: fin_sentiment_score(x['Headline'], x['Text'], 'pos'), axis = 1)
df_articles.info()

<class 'pandas.core.frame.DataFrame'>
Index: 63703 entries, 0 to 63703
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date & Time    63703 non-null  datetime64[ns, UTC]
 1   Date           63703 non-null  object
 2   Time           63703 non-null  object
 3   Ticker         63703 non-null  object
 4   Sector         63703 non-null  object
 5   Source         63703 non-null  object
 6   sentiment_neg  63703 non-null  float64
 7   sentiment_neu  63703 non-null  float64
 8   sentiment_pos  63703 non-null  float64
 9   sentiment_tot  63703 non-null  float64
 10  Headline       63703 non-null  object
 11  Text           63703 non-null  object
 12  URL            63703 non-null  object
 13  finvader       63703 non-null  float64
 14  finvader_neg   63703 non-null  float64
 15  finvader_neu   63703 non-null  float64
 16  finvader_pos   63703 non-null  float64
dtypes: datetime64[ns, UTC](1), float64(8), object(8)
memory usage: 8.7+ MB

In [69]:
df_articles.rename(columns = {'finvader':'finvader_tot'}, inplace = True)
df_articles

,Date & Time,Date,Time,Ticker,Sector,Source,sentiment_neg,sentiment_neu,sentiment_pos,sentiment_tot,Headline,Text,URL,finvader_tot,finvader_neg,finvader_neu,finvader_pos
0,2019-03-15 10:46:42+00:00,2019-03-15,10:46:42,WFC,Finance,The Motley Fool,0.000,0.931,0.069,0.2500,Did Wells Fargo CEO Tim Sloan Earn His $1 Mill...,We learned this week that the scandal-plagued ...,https://www.fool.com/investing/2019/03/14/did-...,0.2869,0.000,0.823,0.177
1,2019-03-15 10:47:26+00:00,2019-03-15,10:47:26,AAPL,Technology,The Motley Fool,0.000,0.748,0.252,0.5248,Don't Underestimate Apple's iPhone Business,The segment is an invaluable asset to Apple's ...,https://www.fool.com/investing/2019/03/14/dont...,0.0396,0.000,0.660,0.340
2,2019-03-15 11:33:00+00:00,2019-03-15,11:33:00,MA,Finance,Forbes,0.060,0.741,0.199,0.7269,A Closer Look At Mastercard's Key Value Drivers,Mastercard has consistently beat street estima...,https://www.forbes.com/sites/greatspeculations...,0.8922,0.042,0.595,0.363
3,2019-03-15 11:52:45+00:00,2019-03-15,11:52:45,BAC,Finance,Benzinga,0.104,0.896,0.000,-0.5367,Jim Cramer Gives His Opinion On Bank Of Americ...,"On CNBC's ""Mad Money Lightning Round"", Jim Cra...",https://feeds.benzinga.com/~r/benzinga/~3/Fwtd...,0.0129,0.034,0.899,0.067
4,2019-03-15 13:29:39+00:00,2019-03-15,13:29:39,GOOGL,Technology,Benzinga,0.085,0.915,0.000,-0.4201,Uber And Waymo Seeking Outside Funding For Aut...,Commercially viable autonomous vehicle (AV) te...,https://feeds.benzinga.com/~r/benzinga/~3/fizU...,-0.3215,0.076,0.734,0.189
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63699,2024-03-15 20:23:00+00:00,2024-03-15,20:23:00,MRK,Healthcare,PRNewsWire,0.018,0.833,0.148,0.8625,FarmSee Ltd Announces the Completion of a Mino...,Cutting edge & AI solution for continuous and ...,https://www.prnewswire.com/news-releases/farms...,0.8458,0.042,0.696,0.262
63700,2024-03-15 21:00:00+00:00,2024-03-15,21:00:00,NVDA,Technology,The Motley Fool,0.000,0.760,0.240,0.9169,"Here's My Top ""Magnificent Seven"" Stock to Buy...",Nvidia believes the long-term data center oppo...,https://www.fool.com/investing/2024/03/15/top-...,0.8700,0.019,0.674,0.307
63701,2024-03-15 21:03:01+00:00,2024-03-15,21:03:01,AAPL,Technology,Business Insider,0.108,0.849,0.043,-0.2732,Tim Cook's comments about iPhone sales in Chin...,Apple has agreed to pay $490 million to settle...,https://www.businessinsider.com/tim-cooks-comm...,0.2789,0.047,0.813,0.140
63702,2024-03-15 22:18:35+00:00,2024-03-15,22:18:35,AAPL,Technology,The Guardian,0.241,0.677,0.083,-0.6486,Apple to pay $490m to settle claims it misled ...,Company denied that Tim Cook deceived investor...,https://www.theguardian.com/technology/2024/ma...,-0.6772,0.211,0.618,0.171
63703,2024-03-15 23:21:00+00:00,2024-03-15,23:21:00,AAPL,Technology,Market Watch,0.081,0.882,0.036,-0.1531,Apple to pay $490 million to settle claims it ...,Apple Inc. has agreed to pay $490 million to s...,https://www.marketwatch.com/story/apple-to-pay...,-0.0798,0.084,0.784,0.133

In [3]:
tech_tickers = ["MSFT", "AAPL", "NVDA", "GOOGL", "AMZN"]
healthcare_tickers = ["LLY", "UNH", "JNJ", "MRK", "ABBV"]
finance_tickers = ["JPM", "V", "MA", "BAC", "WFC"]

def map_sector(ticker):
    if ticker in tech_tickers:
        return "Technology"
    elif ticker in healthcare_tickers:
        return "Healthcare"
    elif ticker in finance_tickers:
        return "Finance"
    else:
        return "Unknown"

df_articles['Sector'] = df_articles['Ticker'].apply(map_sector)
df_articles['Sector'].unique()

array(['Finance', 'Technology', 'Healthcare'], dtype=object)

In [88]:
stock_files = {
    "MSFT": "Microsoft_stock.csv",
    "AAPL": "Apple_stock.csv",
    "NVDA": "Nvidia_stock.csv",
    "GOOGL":"Google_stock.csv",
    "AMZN": "Amazon_stock.csv",
    "JPM":  "JP_Morgan_stock.csv",
    "V":    "Visa_stock.csv",
    "MA":   "Mastercard_stock.csv",
    "BAC":  "Bank_of_America_stock.csv",
    "WFC":  "Wells_Fargo_stock.csv",
    "LLY":  "Eli_Lily.csv",
    "UNH":  "UnitedHealth.csv",
    "JNJ":  "Johnson_and_Johnson_stock.csv",
    "MRK":  "Merck.csv",
    "ABBV": "AbbVie.csv"
}
master_stock_df = pd.DataFrame()
for ticker, file in stock_files.items():    
    stock_df = pd.read_csv('Stock_data/'+file)
    stock_df['Date'] = pd.to_datetime(stock_df['Date'], utc = True)
    stock_df.rename(columns={'Date':'Date & Time'}, inplace=True)
    stock_df['Ticker'] = ticker
    master_stock_df = pd.concat([master_stock_df, stock_df], ignore_index=True)

master_stock_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19185 entries, 0 to 19184
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date & Time   19185 non-null  datetime64[ns, UTC]
 1   Open          19185 non-null  float64
 2   High          19185 non-null  float64
 3   Low           19185 non-null  float64
 4   Close         19185 non-null  float64
 5   Volume        19185 non-null  int64
 6   Dividends     19185 non-null  float64
 7   Stock Splits  19185 non-null  float64
 8   Ticker        19185 non-null  object
dtypes: datetime64[ns, UTC](1), float64(6), int64(1), object(1)
memory usage: 1.3+ MB

# Manipulating Time

Want to merge the stock and sentiment dataframes, but do it along the stock opening and closing times. Thankfully, everthing has been converted to a standard UTC-0 time, although we should note that the stock times currently in the master_stock_df are NOT the stock market opening times, but rather midnight of the index date in EST/EDT.

In [89]:
#don't run this multiple times in a row, or you keep shifting the time repeatedly
master_stock_df['Opening Time'] = master_stock_df['Date & Time'] + timedelta(hours = 9, minutes = 30)
master_stock_df['Closing Time'] = master_stock_df['Date & Time'] + timedelta(hours = 16)
master_stock_df.rename(columns = {'Date & Time':'Market Date'}, inplace = True)
master_stock_df

,Market Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Ticker,Opening Time,Closing Time
0,2019-03-01 05:00:00+00:00,107.265649,107.389169,106.106430,106.923584,23501200,0.0,0.0,MSFT,2019-03-01 14:30:00+00:00,2019-03-01 21:00:00+00:00
1,2019-03-04 05:00:00+00:00,107.389176,107.607720,105.279786,106.667046,26608000,0.0,0.0,MSFT,2019-03-04 14:30:00+00:00,2019-03-04 21:00:00+00:00
2,2019-03-05 05:00:00+00:00,106.657542,106.790567,105.688363,106.134941,19538300,0.0,0.0,MSFT,2019-03-05 14:30:00+00:00,2019-03-05 21:00:00+00:00
3,2019-03-06 05:00:00+00:00,106.296481,107.047123,105.878400,106.182457,17687000,0.0,0.0,MSFT,2019-03-06 14:30:00+00:00,2019-03-06 21:00:00+00:00
4,2019-03-07 05:00:00+00:00,105.849888,105.992416,104.396116,104.890205,25339000,0.0,0.0,MSFT,2019-03-07 14:30:00+00:00,2019-03-07 21:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...
19180,2024-03-22 04:00:00+00:00,175.590161,177.333886,175.144328,176.798874,4084000,0.0,0.0,ABBV,2024-03-22 13:30:00+00:00,2024-03-22 20:00:00+00:00
19181,2024-03-25 04:00:00+00:00,177.343781,177.541927,176.481835,176.878128,4366400,0.0,0.0,ABBV,2024-03-25 13:30:00+00:00,2024-03-25 20:00:00+00:00
19182,2024-03-26 04:00:00+00:00,177.571651,178.106664,176.729525,177.532028,4392400,0.0,0.0,ABBV,2024-03-26 13:30:00+00:00,2024-03-26 20:00:00+00:00
19183,2024-03-27 04:00:00+00:00,178.136391,178.909173,177.155545,178.681305,5073500,0.0,0.0,ABBV,2024-03-27 13:30:00+00:00,2024-03-27 20:00:00+00:00
19184,2024-03-28 04:00:00+00:00,179.325272,180.613247,178.631752,180.415100,5418700,0.0,0.0,ABBV,2024-03-28 13:30:00+00:00,2024-03-28 20:00:00+00:00

In [22]:
open_market_days = master_stock_df['Opening Time'].unique()
closing_market_days = master_stock_df['Closing Time'].unique()
strict_dates = master_stock_df['Date & Time'].unique()
len(open_market_days), len(closing_market_days), len(strict_dates)

(1279, 1279, 1279)

Now let's adjust the time of our articles to match the next market day by closing time and opening times.

In [70]:
df_articles['Date & Time']= df_articles['Date & Time'].sort_values()
open_day = pd.DataFrame(open_market_days, columns= ['Next Open Time'])
close_day = pd.DataFrame(closing_market_days, columns= ['Next Closing Time'])
dates = pd.DataFrame(strict_dates, columns = ['Next Market Date'])
df_int1 = pd.merge_asof(df_articles, open_day, right_on = "Next Open Time", left_on='Date & Time', direction = 'forward')

df_int2 = pd.merge_asof(df_articles, close_day, right_on = 'Next Closing Time', left_on = 'Date & Time', direction = 'forward')
df_int3 = pd.merge_asof(df_articles, dates, right_on = 'Next Market Date', left_on = 'Date & Time',direction = 'forward' )
df_int3
len(df_int1), len(df_int2), len(df_int3)

(63703, 63703, 63703)

In [71]:
common = list(df_articles)
df_a = pd.merge(df_int1, df_int2, on= common)
master_articles_df = pd.merge(df_a, df_int3, on = common)
master_articles_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63703 entries, 0 to 63702
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date & Time        63703 non-null  datetime64[ns, UTC]
 1   Date               63703 non-null  object
 2   Time               63703 non-null  object
 3   Ticker             63703 non-null  object
 4   Sector             63703 non-null  object
 5   Source             63703 non-null  object
 6   sentiment_neg      63703 non-null  float64
 7   sentiment_neu      63703 non-null  float64
 8   sentiment_pos      63703 non-null  float64
 9   sentiment_tot      63703 non-null  float64
 10  Headline           63703 non-null  object
 11  Text               63703 non-null  object
 12  URL                63703 non-null  object
 13  finvader_tot       63703 non-null  float64
 14  finvader_neg       63703 non-null  float64
 15  finvader_neu       63703 non-null  float64
 16  finvader_pos       63703 non-null  float64
 17  Next Open Time     63703 non-null  datetime64[ns, UTC]
 18  Next Closing Time  63703 non-null  datetime64[ns, UTC]
 19  Next Market Date   63703 non-null  datetime64[ns, UTC]
dtypes: datetime64[ns, UTC](4), float64(8), object(8)
memory usage: 9.7+ MB

In [ ]:
#save vanilla sentiment scores for posterity
vanilla_vader_scores = master_articles_df[['sentiment_neg', 'sentiment_neu', 'sentiment_pos', 'sentiment_tot', 'URL']]

In [74]:
master_articles_df.drop(columns = ['sentiment_neg', 'sentiment_neu', 'sentiment_pos', 'sentiment_tot'], inplace = True)
master_articles_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63703 entries, 0 to 63702
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date & Time        63703 non-null  datetime64[ns, UTC]
 1   Date               63703 non-null  object
 2   Time               63703 non-null  object
 3   Ticker             63703 non-null  object
 4   Sector             63703 non-null  object
 5   Source             63703 non-null  object
 6   Headline           63703 non-null  object
 7   Text               63703 non-null  object
 8   URL                63703 non-null  object
 9   finvader_tot       63703 non-null  float64
 10  finvader_neg       63703 non-null  float64
 11  finvader_neu       63703 non-null  float64
 12  finvader_pos       63703 non-null  float64
 13  Next Open Time     63703 non-null  datetime64[ns, UTC]
 14  Next Closing Time  63703 non-null  datetime64[ns, UTC]
 15  Next Market Date   63703 non-null  datetime64[ns, UTC]
dtypes: datetime64[ns, UTC](4), float64(4), object(8)
memory usage: 7.8+ MB

In [79]:
master_articles_df.rename(columns = {'Date & Time': 'Publishing Time'}, inplace = True)
master_articles_df.drop(columns = ['Date', 'Time'], inplace = True)
master_articles_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63703 entries, 0 to 63702
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Publishing Time    63703 non-null  datetime64[ns, UTC]
 1   Ticker             63703 non-null  object
 2   Sector             63703 non-null  object
 3   Source             63703 non-null  object
 4   Headline           63703 non-null  object
 5   Text               63703 non-null  object
 6   URL                63703 non-null  object
 7   finvader_tot       63703 non-null  float64
 8   finvader_neg       63703 non-null  float64
 9   finvader_neu       63703 non-null  float64
 10  finvader_pos       63703 non-null  float64
 11  Next Open Time     63703 non-null  datetime64[ns, UTC]
 12  Next Closing Time  63703 non-null  datetime64[ns, UTC]
 13  Next Market Date   63703 non-null  datetime64[ns, UTC]
dtypes: datetime64[ns, UTC](4), float64(4), object(6)
memory usage: 6.8+ MB

# MERGING

We have two dataframes, master_stock_df and master_articles_df. We can merge them in three different ways:

1. Associate an article with the next open time
2. Associate article with next closing time
3. Associate article with next market date

All are valid considerations. For reference, complete.csv currently uses option 2. 

In the following, we will go with option 1. Changes to other options is done by pairing the obvious columns in each dataframe with each other in the merge

In [104]:
#save master frames of stock, market
# master_stock_df.to_csv('data/master_stock.csv', index = False)
# master_articles_df.to_csv('data/master_articles.csv', index = False)

In [94]:
master_stock_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19185 entries, 0 to 19184
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Market Date   19185 non-null  datetime64[ns, UTC]
 1   Open          19185 non-null  float64
 2   High          19185 non-null  float64
 3   Low           19185 non-null  float64
 4   Close         19185 non-null  float64
 5   Volume        19185 non-null  int64
 6   Dividends     19185 non-null  float64
 7   Stock Splits  19185 non-null  float64
 8   Ticker        19185 non-null  object
 9   Opening Time  19185 non-null  datetime64[ns, UTC]
 10  Closing Time  19185 non-null  datetime64[ns, UTC]
dtypes: datetime64[ns, UTC](3), float64(6), int64(1), object(1)
memory usage: 1.6+ MB

In [93]:
master_articles_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63703 entries, 0 to 63702
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Publishing Time    63703 non-null  datetime64[ns, UTC]
 1   Ticker             63703 non-null  object
 2   Sector             63703 non-null  object
 3   Source             63703 non-null  object
 4   Headline           63703 non-null  object
 5   Text               63703 non-null  object
 6   URL                63703 non-null  object
 7   finvader_tot       63703 non-null  float64
 8   finvader_neg       63703 non-null  float64
 9   finvader_neu       63703 non-null  float64
 10  finvader_pos       63703 non-null  float64
 11  Next Open Time     63703 non-null  datetime64[ns, UTC]
 12  Next Closing Time  63703 non-null  datetime64[ns, UTC]
 13  Next Market Date   63703 non-null  datetime64[ns, UTC]
dtypes: datetime64[ns, UTC](4), float64(4), object(6)
memory usage: 6.8+ MB

In [99]:
df_all = pd.merge(master_articles_df, master_stock_df,left_on = ['Next Open Time', 'Ticker'], right_on = ['Opening Time', 'Ticker'], how = 'outer' )
df_all

,Publishing Time,Ticker,Sector,Source,Headline,Text,URL,finvader_tot,finvader_neg,finvader_neu,...,Market Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Opening Time,Closing Time
0,NaT,AAPL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2019-03-01 05:00:00+00:00,41.887973,42.097075,41.553888,42.053814,103544800,0.0,0.0,2019-03-01 14:30:00+00:00,2019-03-01 21:00:00+00:00
1,NaT,ABBV,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2019-03-01 05:00:00+00:00,62.740368,63.589807,62.354977,62.999920,8567900,0.0,0.0,2019-03-01 14:30:00+00:00,2019-03-01 21:00:00+00:00
2,NaT,AMZN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2019-03-01 05:00:00+00:00,82.756500,83.712997,82.550003,83.586502,99498000,0.0,0.0,2019-03-01 14:30:00+00:00,2019-03-01 21:00:00+00:00
3,NaT,BAC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2019-03-01 05:00:00+00:00,25.918994,26.201778,25.812949,25.901320,45771500,0.0,0.0,2019-03-01 14:30:00+00:00,2019-03-01 21:00:00+00:00
4,NaT,GOOGL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2019-03-01 05:00:00+00:00,56.549999,57.500000,56.549999,57.425999,34086000,0.0,0.0,2019-03-01 14:30:00+00:00,2019-03-01 21:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69428,NaT,MSFT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2024-03-28 04:00:00+00:00,420.202052,421.110417,418.365369,419.962494,21871200,0.0,0.0,2024-03-28 13:30:00+00:00,2024-03-28 20:00:00+00:00
69429,NaT,NVDA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2024-03-28 04:00:00+00:00,900.000000,913.000000,891.929993,903.559998,43521200,0.0,0.0,2024-03-28 13:30:00+00:00,2024-03-28 20:00:00+00:00
69430,NaT,UNH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2024-03-28 04:00:00+00:00,495.000000,495.869995,489.299988,494.700012,3820000,0.0,0.0,2024-03-28 13:30:00+00:00,2024-03-28 20:00:00+00:00
69431,NaT,V,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2024-03-28 04:00:00+00:00,277.975547,279.283124,276.608082,278.564453,5844400,0.0,0.0,2024-03-28 13:30:00+00:00,2024-03-28 20:00:00+00:00
69432,NaT,WFC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2024-03-28 04:00:00+00:00,57.330408,57.748009,57.230981,57.628693,14619000,0.0,0.0,2024-03-28 13:30:00+00:00,2024-03-28 20:00:00+00:00

Double-check that on days with article, we have everything correct.

In [96]:
df_all[df_all['Publishing Time'].notna()]

,Publishing Time,Ticker,Sector,Source,Headline,Text,URL,finvader_tot,finvader_neg,finvader_neu,...,Market Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Opening Time,Closing Time
150,2019-03-15 10:47:26+00:00,AAPL,Technology,The Motley Fool,Don't Underestimate Apple's iPhone Business,The segment is an invaluable asset to Apple's ...,https://www.fool.com/investing/2019/03/14/dont...,0.0396,0.000,0.660,...,2019-03-15 04:00:00+00:00,44.428467,45.024531,44.161680,44.733707,156171600,0.0,0.0,2019-03-15 13:30:00+00:00,2019-03-15 20:00:00+00:00
153,2019-03-15 11:52:45+00:00,BAC,Finance,Benzinga,Jim Cramer Gives His Opinion On Bank Of Americ...,"On CNBC's ""Mad Money Lightning Round"", Jim Cra...",https://feeds.benzinga.com/~r/benzinga/~3/Fwtd...,0.0129,0.034,0.899,...,2019-03-15 04:00:00+00:00,26.016197,26.166426,25.857130,25.892477,82346200,0.0,0.0,2019-03-15 13:30:00+00:00,2019-03-15 20:00:00+00:00
154,2019-03-15 13:29:39+00:00,GOOGL,Technology,Benzinga,Uber And Waymo Seeking Outside Funding For Aut...,Commercially viable autonomous vehicle (AV) te...,https://feeds.benzinga.com/~r/benzinga/~3/fizU...,-0.3215,0.076,0.734,...,2019-03-15 04:00:00+00:00,59.900002,60.085999,59.350498,59.514999,51886000,0.0,0.0,2019-03-15 13:30:00+00:00,2019-03-15 20:00:00+00:00
158,2019-03-15 11:33:00+00:00,MA,Finance,Forbes,A Closer Look At Mastercard's Key Value Drivers,Mastercard has consistently beat street estima...,https://www.forbes.com/sites/greatspeculations...,0.8922,0.042,0.595,...,2019-03-15 04:00:00+00:00,222.284859,226.112319,222.275135,224.567734,3894200,0.0,0.0,2019-03-15 13:30:00+00:00,2019-03-15 20:00:00+00:00
164,2019-03-15 10:46:42+00:00,WFC,Finance,The Motley Fool,Did Wells Fargo CEO Tim Sloan Earn His $1 Mill...,We learned this week that the scandal-plagued ...,https://www.fool.com/investing/2019/03/14/did-...,0.2869,0.000,0.823,...,2019-03-15 04:00:00+00:00,43.222540,43.721723,43.033193,43.601231,46117300,0.0,0.0,2019-03-15 13:30:00+00:00,2019-03-15 20:00:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69305,2024-03-15 14:00:00+00:00,NVDA,Technology,The Motley Fool,3 Brilliant Reasons to Buy Nvidia Stock Right Now,Nvidia has been an incredible outperformer ove...,https://www.fool.com/investing/2024/03/15/3-br...,0.6553,0.000,0.669,...,2024-03-18 04:00:00+00:00,903.880005,924.049988,870.849976,884.549988,66897600,0.0,0.0,2024-03-18 13:30:00+00:00,2024-03-18 20:00:00+00:00
69306,2024-03-15 14:31:07+00:00,NVDA,Technology,Zacks Investment Research,Is It Worth Investing in Nvidia (NVDA) Based o...,The recommendations of Wall Street analysts ar...,https://www.zacks.com/stock/news/2241323/is-it...,0.0258,0.021,0.895,...,2024-03-18 04:00:00+00:00,903.880005,924.049988,870.849976,884.549988,66897600,0.0,0.0,2024-03-18 13:30:00+00:00,2024-03-18 20:00:00+00:00
69307,2024-03-15 15:15:00+00:00,NVDA,Technology,WSJ,"Hey ChatGPT, Why Isn't My AI Fund Up Like Nvidia?",It's harder to hitch your wagon to Wall Street...,https://www.wsj.com/articles/ai-disruptive-inn...,0.3544,0.115,0.714,...,2024-03-18 04:00:00+00:00,903.880005,924.049988,870.849976,884.549988,66897600,0.0,0.0,2024-03-18 13:30:00+00:00,2024-03-18 20:00:00+00:00
69308,2024-03-15 16:19:22+00:00,NVDA,Technology,The Motley Fool,"Nvidia Stock Has 12% Upside, According This Wa...",Wedbush Securities recently raised its price t...,https://www.fool.com/investing/2024/03/15/nvid...,0.5838,0.000,0.804,...,2024-03-18 04:00:00+00:00,903.880005,924.049988,870.849976,884.549988,66897600,0.0,0.0,2024-03-18 13:30:00+00:00,2024-03-18 20:00:00+00:00
69309,2024-03-15 21:00:00+00:00,NVDA,Technology,The Motley Fool,"Here's My Top ""Magnificent Seven"" Stock to Buy...",Nvidia believes the long-term data center oppo...,https://www.fool.com/investing/2024/03/15/top-...,0.8700,0.019,0.674,...,2024-03-18 04:00:00+00:00,903.880005,924.049988,870.849976,884.549988,66897600,0.0,0.0,2024-03-18 13:30:00+00:00,2024-03-18 20:00:00+00:00

Do some final renaming and organizing.

In [100]:
df_all['Market Date'] = df_all['Market Date'].dt.date
df_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69433 entries, 0 to 69432
Data columns (total 24 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Publishing Time    63703 non-null  datetime64[ns, UTC]
 1   Ticker             69433 non-null  object
 2   Sector             63703 non-null  object
 3   Source             63703 non-null  object
 4   Headline           63703 non-null  object
 5   Text               63703 non-null  object
 6   URL                63703 non-null  object
 7   finvader_tot       63703 non-null  float64
 8   finvader_neg       63703 non-null  float64
 9   finvader_neu       63703 non-null  float64
 10  finvader_pos       63703 non-null  float64
 11  Next Open Time     63703 non-null  datetime64[ns, UTC]
 12  Next Closing Time  63703 non-null  datetime64[ns, UTC]
 13  Next Market Date   63703 non-null  datetime64[ns, UTC]
 14  Market Date        69433 non-null  object
 15  Open               69433 non-null  float64
 16  High               69433 non-null  float64
 17  Low                69433 non-null  float64
 18  Close              69433 non-null  float64
 19  Volume             69433 non-null  int64
 20  Dividends          69433 non-null  float64
 21  Stock Splits       69433 non-null  float64
 22  Opening Time       69433 non-null  datetime64[ns, UTC]
 23  Closing Time       69433 non-null  datetime64[ns, UTC]
dtypes: datetime64[ns, UTC](6), float64(10), int64(1), object(7)
memory usage: 12.7+ MB

In [101]:
reorder = [
    'Publishing Time',
    'Market Date',
    'Ticker',
    'Sector',
    'finvader_neg',
    'finvader_neu',
    'finvader_pos',
    'finvader_tot',
    'Source',
    'Headline',
    'Text',
    'URL',
    'Open',
    'High',
    'Low',
    'Close',
    'Volume',
    'Dividends',
    'Stock Splits'

]

df_all = df_all[reorder]
df_all['Sector'] = df_all['Ticker'].apply(map_sector)
df_all

/var/folders/tg/nkrt27q937bgzsnrzszxn7bc0000gn/T/ipykernel_16922/824062894.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_all['Sector'] = df_all['Ticker'].apply(map_sector)

,Publishing Time,Market Date,Ticker,Sector,finvader_neg,finvader_neu,finvader_pos,finvader_tot,Source,Headline,Text,URL,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,NaT,2019-03-01,AAPL,Technology,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.887973,42.097075,41.553888,42.053814,103544800,0.0,0.0
1,NaT,2019-03-01,ABBV,Healthcare,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62.740368,63.589807,62.354977,62.999920,8567900,0.0,0.0
2,NaT,2019-03-01,AMZN,Technology,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,82.756500,83.712997,82.550003,83.586502,99498000,0.0,0.0
3,NaT,2019-03-01,BAC,Finance,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.918994,26.201778,25.812949,25.901320,45771500,0.0,0.0
4,NaT,2019-03-01,GOOGL,Technology,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56.549999,57.500000,56.549999,57.425999,34086000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69428,NaT,2024-03-28,MSFT,Technology,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,420.202052,421.110417,418.365369,419.962494,21871200,0.0,0.0
69429,NaT,2024-03-28,NVDA,Technology,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,900.000000,913.000000,891.929993,903.559998,43521200,0.0,0.0
69430,NaT,2024-03-28,UNH,Healthcare,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,495.000000,495.869995,489.299988,494.700012,3820000,0.0,0.0
69431,NaT,2024-03-28,V,Finance,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,277.975547,279.283124,276.608082,278.564453,5844400,0.0,0.0
69432,NaT,2024-03-28,WFC,Finance,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57.330408,57.748009,57.230981,57.628693,14619000,0.0,0.0

In [102]:
df_all.iloc[181]

Publishing Time                            2019-03-15 16:36:05+00:00
Market Date                                               2019-03-18
Ticker                                                           JPM
Sector                                                       Finance
finvader_neg                                                     0.0
finvader_neu                                                    0.84
finvader_pos                                                    0.16
finvader_tot                                                  0.0464
Source                                               The Motley Fool
Headline           Why Warren Buffett Thinks JPMorgan's Stock Cou...
Text               The billionaire investor recently revealed his...
URL                https://www.fool.com/investing/2019/03/15/why-...
Open                                                       91.201688
High                                                       92.263066
Low                                                        91.158887
Close                                                      91.749496
Volume                                                      12935500
Dividends                                                        0.0
Stock Splits                                                     0.0
Name: 181, dtype: object

We finalize by reading it into a csv

In [103]:
# df_all.to_csv('data/complete_next_open.csv', index = False)